---
title: "analysis on 10x data"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This is an example analysis with a dataset of trple-negative breast cancer, sequenced with 10x. The data has been obtained from Campbell at al 2019 and is currently available at ![]  


```{r}

library(Matrix)

counts_SA <- as.matrix(t(readMM("clonealign-processed-data/SA501/10X/20171026_SA501X2XB00096/outs/filtered_gene_bc_matrices/hg19/matrix.mtx")))

genes <- read.table("clonealign-processed-data/SA501/10X/20171026_SA501X2XB00096/outs/filtered_gene_bc_matrices/hg19/genes.tsv")
  
barcodes <-  read.table("clonealign-processed-data/SA501/10X/20171026_SA501X2XB00096/outs/filtered_gene_bc_matrices/hg19/barcodes.tsv")

colnames(counts_SA) <-  genes$V2

rownames(counts_SA) <- barcodes$V1

```

In rcongas we have 

```{r}

library("rcongas")

mat_pre <- as.matrix(preprocess_sc(mat = counts_SA, filter_upper_quantile = T, perc_cells_gene_expr = 0.05,upper_quantile = 0.95))
```


```{r}

#clones_dataA <- read.csv("clonealign-processed-data/SA501/cnv/SA501X3F-cluster_A.segments.csv")[,c(1,2,3,7)]

clones_dataA$tot <-  clones_dataA$integer_copy_number
clones_dataA$chr <- paste0("chr", clones_dataA$chr)


clones_dataA2 <- clones_dataA %>%  filter(!(chr %in% c("chr15", "chr16", "chr18")))

inp2 <-  get_data(t(mat_pre), cnv_data = clones_dataA, type = "fixed_binning", startsWithchr = F,  correct_bins = F, genome = "hg19", custom_gene_matrix = counts_SA)


inp3 <- filter_segments.rcongas(X = inp2, filter_mu = 10)



pheatmap::pheatmap(((inp3$data$counts / colSums(t(mat_pre))) ) / inp3$data$cnv$ploidy_real, show_rownames = F, show_colnames = T, cluster_cols = F, cutree_rows = 2)



```



```{r}
set.seed(3)
res <- best_cluster(inp3,model = "MixtureGaussianOld", clusters = 1:4, steps = 800, lr = 0.01, param_list = list("theta_scale" = 3.2, "theta_rate" = 0.5, "cnv_var" = 0.60) , method = "BIC",  MAP = T, posteriors = T, step_post = 100)

res_filt <-  filter_clusters(res, abundance = 0.05)
```



```{r}

plot_counts_rna_segments(res_filt, z_score = T, normalised = T)


```

```{r}
library(Seurat)
```


```{r}
rerun <-  run_complete(
  res_filt
  
)

```


```{r}
de <- calculate_DE(rerun, counts_SA[rownames(mat_pre),] %>%  t, clone1 = "1", clone2 = "2", method = "DESeq2")

```

```{r}
clones_dataB$tot <-  clones_dataB$integer_copy_number

c18 <-  clones_dataA %>%  filter(chr %in% c(15,16,18)) 


inp4 <-  get_data(t(mat_pre), cnv_data = c18, type = "fixed_binning", startsWithchr = F, correct_bins = F, genome = "hg19")


inp4 <- inp4[,!is.na(inp4$cnv$mu) & inp4$cnv$mu > 5]

```



```{r}
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(Rfast)

#df_cnv_A <- read.csv("clonealign-processed-data/SA501/cnv/SA501X3F-cluster_A.segments.csv")
#df_cnv_B <- read.csv("clonealign-processed-data/SA501/cnv/SA501X3F-cluster_B.segments.csv")
#df_cnv_C <- read.csv("clonealign-processed-data/SA501/cnv/SA501X3F-cluster_C.segments.csv")

df_cnv_AB <- rbind(df_cnv_A %>% dplyr::mutate(clone = "A"), df_cnv_B%>% dplyr::mutate(clone = "B"))
df_cnv <- rbind(df_cnv_AB, df_cnv_C %>% dplyr::mutate(clone = "C"))

txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene

g <- genes(txdb, single.strand.genes.only=FALSE)

df_cnv <- dplyr::mutate(df_cnv, chr = paste0("chr", chr)) %>% filter(chr != "chrX", chr != "chrY")

cnv_gr <- makeGRangesFromDataFrame(df_cnv, keep.extra.columns = TRUE)

olaps <- findOverlaps(g, cnv_gr)

df_gene <- data.frame(entrezgene = names(g)[queryHits(olaps)], 
           copy_number = mcols(cnv_gr)$integer_copy_number[subjectHits(olaps)],
           clone = mcols(cnv_gr)$clone[subjectHits(olaps)])

library(org.Hs.eg.db)

entrezgene_ensembl_map <- as.list(org.Hs.egENSEMBL)
entrezgene_ensembl_map <- lapply(entrezgene_ensembl_map, `[`, 1)

df_gene <- dplyr::filter(df_gene, entrezgene %in% names(entrezgene_ensembl_map)) %>% 
  dplyr::mutate(ensembl_gene_id = unlist(entrezgene_ensembl_map[entrezgene])) %>% 
  dplyr::select(ensembl_gene_id, entrezgene, copy_number, clone) %>% 
  tidyr::drop_na()

df_gene <- dplyr::count(df_gene, ensembl_gene_id) %>% 
  dplyr::filter(n == length(unique(df_gene$clone))) %>% 
  dplyr::inner_join(df_gene) %>% 
  dplyr::select(-n)


df_gene_expanded <- tidyr::spread(df_gene, clone, copy_number)

cnv_mat <- dplyr::select(df_gene_expanded, -ensembl_gene_id, -entrezgene) %>% 
  as.matrix()

rownames(cnv_mat) <- df_gene_expanded$ensembl_gene_id

#keep_gene <- rowMins(cnv_mat) <= 6 & rowVars(cnv_mat) > 0

#cnv_mat <- cnv_mat[keep_gene,]

```


```{r}

devtools::unload("clonealign")


library(clonealign)
library(SingleCellExperiment)


sce <- SingleCellExperiment(list(counts = t(as.matrix(counts_SA))) )

cgenes <-  intersect(colnames(counts_SA), rownames(cnv_mat))

ca_data <- clonealign::preprocess_for_clonealign(counts_SA[,cgenes], cnv_mat[cgenes,])

cal <- clonealign::run_clonealign(ca_data$gene_expression_data, ca_data$copy_number_data)
library(tensorflow)
install_tensorflow(version = 1.5)

devtools::load_all("kieranrcampbell-clonealign-4d6c340/")

cal <-  clonealign(ca_data$gene_expression_data, ca_data$copy_number_data)

clonealign_inf <-  dplyr::tibble(clone = cal$clone, cell = ca_data$retained_cells)


intersection_congas_clonealign <- dplyr::inner_join(get_clusters(new_run_buono),clonealign_inf)

table(intersection_congas_clonealign$clone, intersection_congas_clonealign$cluster)

```

```{r}
AB <- rbind(df_cnv_A%>%  mutate(cluster = "A"), df_cnv_B %>%  mutate(cluster = "B", integer_copy_number = integer_copy_number -0.1)) 
ABC <- rbind(AB, df_cnv_C %>%  mutate(cluster = "C", integer_copy_number = integer_copy_number - 0.2)) 
ABC <-  ABC[, c(1,2,3,7,8)] %>% filter(chr != "chrX", chr != "chrY")
#ABC$chr <-  paste0("chr", ABC$chr)
cp <-  get_clones_ploidy(new_run_buono)
cp <- cp[,-c(5,6)]
colnames(ABC)[4] <-"CNV"
colnames(cp)[5] <- "CNV"
#cp$CNV <- round(cp$CNV) + 0.1 * as.numeric(cp$cluster)
clonealign_congas_merges <- rbind(ABC,cp)
clonealign_congas_merges$chr <- factor(clonealign_congas_merges$chr, levels = mixedsort(unique(clonealign_congas_merges$chr)))

cols <- RColorBrewer::brewer.pal(4, "Paired")
names(cols) <-  c("1", "A", "2", "B")

(ggplot(clonealign_congas_merges %>%  filter(cluster != "C")) + geom_segment(aes(x = from, y = CNV, xend = to, yend = CNV, color = cluster)) +  facet_wrap(.~chr, scales = "free") + scale_color_manual(values = cols) + theme_light() ) %>% ggsave(filename = "true_vs_inf.pdf", width = 12, height = 12)
```

