---
title: "Fitting a model"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Fitting a model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
# options(crayon.enabled = FALSE)

# knitr::opts_chunk$set(
#   collapse = TRUE,
#   comment = "%>"
# )

# old_hooks <- fansi::set_knit_hooks(knitr::knit_hooks, 
#                                    which = c("output", "message", "error"))

options(crayon.enabled = FALSE)
# options(pillar.bold = TRUE, pillar.subtle_num = TRUE)
# 
# colourise_chunk <- function(type) {
#   function(x, options) {
#     lines <- x
#     if (type != "output") {
#       # lines <- crayon::red(lines)
#     }
#     paste0(
#       '<div class="sourceCode"><pre class="sourceCode"><code class="sourceCode">',
#       paste0(
#         fansi::sgr_to_html(htmltools::htmlEscape(lines)),
#         collapse = "\n"
#       ),
#       "</code></pre></div>"
#     )
#   }
# }
# 
# knitr::knit_hooks$set(
#   output = colourise_chunk("output"),
#   message = colourise_chunk("message"),
#   warning = colourise_chunk("warning"),
#   error = colourise_chunk("error")
# )

knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

```{r, warning=FALSE, message=FALSE}
library(Rcongas)
library(dplyr)
```

```{r}
data("satpathy_bcc")
```

Hyperparameters can be computed from data.


```{r}
satpathy_bcc_hp = auto_config_run(
  satpathy_bcc, 
  K = 1:3
)
```

Parameters are a list.
```{r}
satpathy_bcc_hp
```

Fitting uses `reticulate` to interface with the Python CONGAS package, which implements the models in Pyro.
```{r}
# Run Python
satpathy_bcc = fit_congas(
  satpathy_bcc,
  K = 1:3,
  model_parameters = satpathy_bcc_hp,
  steps = 500
)
```

The new object has more information.
```{r}
satpathy_bcc
```

```{r, fig.width=5, fig.height=3}
satpathy_bcc %>% 
  plot()
```
