---
title: "CONFETTI without bulk DNA"
author: "Salvatore Milite"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


We try to analyze a glioblastome smart-seq dataset from (Patel et al., 2014). The dataset with the associated BAF is taken from 

```{r exploratory}

load("glioblastoma_TPM.rda")

chr_cnv <- data.frame(chr = names(hg38_karyo), start = rep(1,length(hg38_karyo)), end = hg38_karyo, tot = rep(2, length(hg38_karyo)))

express <- get_data(glioblastoma_TPM, cnv_data = chr_cnv, type = "fixed_binning")

pheatmap::pheatmap(express$counts, cluster_cols = F,  show_rownames = F)



```

We can see a fairly variagate landscape, with some interesting changes in chromosomes 9,14 and maybe 13. Now let's segment the genome.

```{r}
library(ggpubr)

load("AF.rda")

cov_tr <-  20

good_sites <- which(AF_info$coverage > cov_tr)



MAF <- AF_info$minor[good_sites] / AF_info$coverage[good_sites]


MAF_l <- MAF %>% dplyr::as_tibble(rownames = "pos") %>% tidyr::separate(pos, c("chr", "start"))

res <- segment_genome(MAF_l, steps = 200L, param_list = list('t'=1e-8), filter_size = 25)

segs_df <- from_inference_to_segments(res, MAF_l)

#segs_df$tot[segs_df$tot == 5] <- 4

segs_df_corr <- simplify_segs(segs_df)

ggpubr::ggarrange(plot_MAF(MAF_l, k = 5), plot_MAF(MAF_l, k = 25), align = "hv", common.legend = T, labels = c("A", "B"), legend = "none", font.label = list(size = 12))

```


```{r}



binned_express <- get_data(glioblastoma_TPM, cnv_data = segs_df_corr, type = "fixed_binning", correct_bins = F, fun = mean)

binned_express <- binned_express[, binned_express$cnv$mu > 50]

interesting_vals <- c("5:224633:180278393", "10:3154461:133786586", "13:21086599:101294428", "14:20216560:51716188 ")
binned_express_filt <- binned_express[,which(colnames(binned_express$counts)  %in% interesting_vals)]

pheatmap::pheatmap(binned_express$counts, cluster_cols = F,  show_rownames = F, cluster_rows = T, cutree_rows = 3)
```


```{r}
set.seed(3)

subclones <- best_cluster(binned_express, clusters = 1:4, model = "MixtureGaussianNorm", steps = 350L, lr = 0.05, param_list = list(a = 3, b = 50), method = "BIC") 

```

```{r}
best_model <- subclones$models[[2]]
row_annot <- as.data.frame(factor(best_model$parameters$assignement))
colnames(row_annot) <-  "cluster"
pheatmap::pheatmap(binned_express$counts[names(sort(best_model$parameters$assignement)),], cluster_cols = F,  show_rownames = F, cluster_rows = F, annotation_row = row_annot, gaps_row = which(!duplicated(sort(row_annot$cluster))) - 1)

```

```{r}
load("MGH31_SNPs_per_cell.rda")
all_cells <- names(subclones$models[[subclones$best_K]]$parameters$assignement)

normal_cells <- all_cells[subclones$models[[subclones$best_K]]$parameters$assignement == 3]
tumor_cells <- all_cells[subclones$models[[subclones$best_K]]$parameters$assignement != 3]


ref_normal <- rowSums(MGH31_SNPs_per_cell$ref[,normal_cells])
alt_normal <- rowSums(MGH31_SNPs_per_cell$alt[,normal_cells])
min_normal <- pmin(ref_normal, alt_normal)
maj_normal <- pmax(ref_normal, alt_normal)
cov_normal <- ref_normal + alt_normal

ref_tumor <- rowSums(MGH31_SNPs_per_cell$ref[,tumor_cells])
alt_tumor <- rowSums(MGH31_SNPs_per_cell$alt[,tumor_cells])
min_tumor <- pmin(ref_tumor, alt_tumor)
maj_tumor <- pmax(ref_tumor, alt_tumor)
cov_tumor <- ref_tumor + alt_tumor

filter <- which(cov_normal > 30)

MAF_normal <- min_normal[filter] / cov_normal[filter]
MAF_tumor <- min_tumor[filter] / cov_tumor[filter]

par(mfrow = c(2,1))
plot(y = MAF_tumor[grep(names(MAF_tumor),pattern = "")], as.numeric(do.call(rbind, strsplit(names(MAF_tumor),split = ":"))[,2]))
plot(y = MAF_normal[grep(names(MAF_normal),pattern = "")],as.numeric(do.call(rbind, strsplit(names(MAF_normal),split = "7:"))[,2]))
```

```{r}


cov_tr <-  40

good_sites <- which(cov_tumor > cov_tr)



MAF <- min_tumor[good_sites] / cov_tumor[good_sites]

MAF <-  MAF[MAF > 0.10]

MAF <-  MAF[grep(names(MAF), pattern = "10:|14:|13:|19:",invert = T)]

MAF_l <- MAF %>% dplyr::as_tibble(rownames = "pos") %>% tidyr::separate(pos, c("chr", "start"))

res <- segment_genome(MAF_l, steps = 200L, param_list = list('t' =1e-8), filter_size = 33)

segs_df <- from_inference_to_segments(res, MAF_l)

segs_df$tot[segs_df$tot == 6] <- 2

segs_df$tot[segs_df$tot == 5] <- 4


segs_df_corr2 <- simplify_segs(segs_df)

ggpubr::ggarrange(plot_MAF(MAF_l, k = 5), plot_MAF(MAF_l, k = 11), align = "hv", common.legend = T, labels = c("A", "B"), legend = "none", font.label = list(size = 12))

```

```{r}
binned_express2 <- get_data(glioblastoma_TPM, cnv_data = segs_df_corr2, type = "fixed_binning", correct_bins = F, fun = mean)

binned_express2 <- binned_express2[, binned_express2$cnv$mu > 50]


LOH <- c("10:3154461:133786586", "13:21086599:101294428", "14:20216560:51716188")


#binned_express_filt2 <- binned_express2[,which(colnames(binned_express2$counts)  %in% interesting_vals)]



final_expr <- bind_confettti(binned_express2[,grep(colnames(binned_express2$counts),pattern = "11:", invert = T)], binned_express[1:75,which(colnames(binned_express$counts)  %in% LOH)]) 


pheatmap::pheatmap(final_expr$counts, cluster_cols = F,  show_rownames = F, cluster_rows = T, cutree_rows = 3)
```

```{r}
set.seed(3)

#init_gauss <- kmeans_inits(final_expr)

subclones2 <- best_cluster(final_expr[tumor_cells,], clusters = 1:4, model = "MixtureGaussianNorm", steps = 300L, lr = 0.1, param_list = list(a = 9, b = 50), method = "BIC", filt_merge = 0.1) 
```


```{r}

best_model2 <- subclones2$models[[4]]
row_annot <- as.data.frame(factor(best_model2$parameters$assignement))
colnames(row_annot) <-  "cluster"

pheatmap::pheatmap(final_expr$counts[names(sort(best_model2$parameters$assignement)),], cluster_cols = F,  show_rownames = F, cluster_rows = F,annotation_row = row_annot, gaps_row = which(!duplicated(sort(row_annot$cluster))) - 1)

```


```{r}

c1_3 <- round(best_model2$parameters$cnv_probs[1,] - best_model2$parameters$cnv_probs[3,] + 0.1)
c2_3 <- round(best_model2$parameters$cnv_probs[2,] - best_model2$parameters$cnv_probs[3,] + 0.1)
c1_4 <- round(best_model2$parameters$cnv_probs[1,] - best_model2$parameters$cnv_probs[4,] + 0.1)

c1 <- round(best_model2$parameters$cnv_probs[1,] + ifelse(best_model2$parameters$cnv_probs[1,] > 0, 0.15, -0.25 ))
c2 <- round(best_model2$parameters$cnv_probs[2,] + ifelse(best_model2$parameters$cnv_probs[2,] > 0, 0.15, -0.25 ))
c3 <- round(best_model2$parameters$cnv_probs[3,] + ifelse(best_model2$parameters$cnv_probs[3,] > 0, 0.15, -0.25 ))
c4 <- round(best_model2$parameters$cnv_probs[4,] + ifelse(best_model2$parameters$cnv_probs[4,] > 0, 0.15, -0.35 ))
  

bin_mat <- rbind("1" = c1, "2" = c2, "3" = c3, "4" = c4)
bin_mat <- bin_mat[, gtools::mixedorder(colnames(bin_mat))]
bin_mat[,c(6,11,19,13)] <- 0
bin_mat[c(1,3,4),20] <- 1

pheatmap::pheatmap(bin_mat, cluster_cols = F, treeheight_row = 100, clustering_distance_rows = "binary")

```
```{r}

p1 <- MAF_clust_plot(MGH31_SNPs_per_cell$ref, MGH31_SNPs_per_cell$tot_coverage, names(best_model2$parameters$assignement[best_model2$parameters$assignement == 1]) , names(best_model2$parameters$assignement[best_model2$parameters$assignement==2]) ,"^5:", filt = 20, labels = c("2", "1"))

p2 <- MAF_clust_plot(MGH31_SNPs_per_cell$ref, MGH31_SNPs_per_cell$tot_coverage, names(best_model2$parameters$assignement[best_model2$parameters$assignement == 2]) , names(best_model2$parameters$assignement[best_model2$parameters$assignement==1]) ,"^13:", filt = 20, labels = c("4", "1"))

p3 <- MAF_clust_plot(MGH31_SNPs_per_cell$ref, MGH31_SNPs_per_cell$tot_coverage, names(best_model2$parameters$assignement[best_model2$parameters$assignement == 3]) , names(best_model2$parameters$assignement[best_model2$parameters$assignement==1]) ,"^14:", filt = 20, labels = c("3", "1"))

p4 <- MAF_clust_plot(MGH31_SNPs_per_cell$ref, MGH31_SNPs_per_cell$tot_coverage, names(best_model2$parameters$assignement[best_model2$parameters$assignement == 2]) , names(best_model2$parameters$assignement[best_model2$parameters$assignement==1]) ,"^20:", filt = 20, labels = c("2", "1"))


ggpubr::ggarrange(p1,p2,p3,p4, ncol=2, nrow = 2, labels = c("5", "13", "14", "20"))

```

```{r}

df_norm_tum <-  calculate_DGE(best_model, glioblastoma_TPM, clone1 = 1, clone2 = 2, normalize = F)
  
df_5_no5 <- calculate_DGE(best_model2, glioblastoma_TPM[,best_model2$dim_names$cell_names], clone1 = 2, clone2 = NULL, normalize = F)
  
df_14_no14 <- calculate_DGE(best_model2, glioblastoma_TPM[,best_model2$dim_names$cell_names], clone1 = 1, clone2 = 3, normalize = F)


so <- CreateSeuratObject(glioblastoma_TPM[,names(c_fin)])
so <- NormalizeData(so)
so <- FindVariableFeatures(so, selection.method = "vst", nfeatures = 6000)

so <- RunUMAP(so, features = VariableFeatures(object = so))

ump2 <-  as.matrix(ump2)
colnames(ump2) <- paste0("UMAP2_", 1:2)
rownames(ump2) <- rownames(as.matrix(binned_express$counts))

so[["umap2"]] <- CreateDimReducObject(embeddings = as.matrix(ump2), key = "UMAP2_", assay = DefaultAssay(so))

fp <- FeaturePlot(so, features = c("KCNMB4", "CLDN11" ,"MOG" ,"CD63" ,"PSMA7" ,"SOD1" , "EGFR" , "C1S", "SYNE2" ))


so@meta.data$clust1 <-  best_model$parameters$assignement 

nor <- best_model$parameters$assignement[best_model$parameters$assignement == 2]
nor[nor == 2] <- 0
c_fin <- c(nor, best_model2$parameters$assignement )
c_fin[c_fin == 4] <- 1
c_fin <- sort(c_fin)
so@meta.data$clust1 <-  c_fin


so2 <- CreateSeuratObject(glioblastoma_TPM[,best_model2$dim_names$cell_names])
so2@meta.data$clust2  <- best_model2$parameters$assignement 


vp2 <- VlnPlot(so, features = c("KCNMB4", "CLDN11" ,"MOG","CD63" ,"PSMA7" ,"SOD1" , "EGFR" , "C1S", "SYNE2" ),  group.by = "clust1", pt.size = 0.5)
```

```{r}





```


